apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-canonical-mp
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: terraform-google-canonical-mp
  source:
    repo: https://github.com/g-awmalik/terraform-google-canonical-mp
    sourceType: git
  version: 0.0.1
  actuationTool:
    type: Terraform
    version: '>= 0.13'
  description:
    tagline: WordPress Google Click to Deploy Solution
    detailed: This module deloys a WordPress Google Click to Deploy Solution from Marketplace.
    preDeploy: To deploy this blueprint you must have an active billing account and billing permissions.
  deploymentDuration:
    configuration: 60
    deployment: 300
  costEstimate:
    description: Wordpress cost details
    url: https://cloud.google.com/products/calculator#id=d2a82f67-ff05-4179-9e15-9682ef77a663
  architecture:
    diagram: assets/wp-architecture.png
    description:
    - 1. Clients request content by querying the web url.
    - 2. Requests reach GCP via a public IP and are evaluated by the firewall.
    - 3. Valid requests pass through the firewall and reach the wordpress GCE instance to serve content.
  documentation:
  - title: Hosting a Static Website
    url: https://cloud.google.com/storage/docs/hosting-static-website
  subBlueprints:
  - name: couchbase-mig
    location: modules/couchbase-mig
  examples:
  - name: couchbase
    location: examples/couchbase
  - name: wordpress_simple
    location: examples/wordpress_simple
  variables:
  - name: boot_disk_size
    description: The boot disk size for the VM instance in GBs
    type: string
    default: "10"
  - name: boot_disk_type
    description: The boot disk type for the VM instance.
    type: string
    default: pd-standard
  - name: enable_logging
    description: Enable cloud logging for the VM instance.
    type: bool
    required: true
  - name: enable_monitoring
    description: Enable cloud monitoring for the VM instance.
    type: bool
    required: true
  - name: install_phpmyadmin
    description: Install phpMyAdmin on the VM instance
    type: bool
    default: true
  - name: ip_source_ranges
    description: A map of source IP ranges for accessing the VM instance over HTTP and/or HTTPS with the port no. as the key and the range as the value.
    type: map(string)
    required: true
  - name: machine_type
    description: The machine type to create, e.g. e2-small
    type: string
    default: n2-standard-4
  - name: name
    description: The name of the VM instance for the deployment.
    type: string
    required: true
  - name: network_interfaces
    description: The network interfaces to attach the VM instance by specifying the network, subnetwork and external IPs, public access is required
    type: |-
      list(object({
          network     = string
          subnetwork  = string
          external_ip = string
        }))
    required: true
  - name: project_id
    description: The ID of the project in which to provision resources.
    type: string
    required: true
  - name: solution_metadata
    description: The solution specific metadata to be applied to the VM instance
    type: map(string)
    default: {}
  - name: source_image
    description: The image name for the disk for the VM instance.
    type: string
    required: true
  - name: source_image_project
    description: The project name where the solution image is stored.
    type: string
    default: click-to-deploy-images
  - name: zone
    description: The zone for the solution to be deployed.
    type: string
    default: us-west1-a
  outputs:
  - name: instance_machine_type
    description: Machine type for the wordpress compute instance
  - name: instance_nat_ip
    description: Machine type for the wordpress compute instance
  - name: instance_self_link
    description: Self-link for the Wordpress compute instance
  - name: instance_zone
    description: Zone for the wordpress compute instance
  roles:
  - level: Project
    roles:
    - roles/compute.admin
  services:
  - cloudresourcemanager.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - compute.googleapis.com
  - iam.googleapis.com
